# Site settings
title: 武汉志愿者
description: 致力于分享新型冠状病毒相关信息
favicon: /assets/img/avatar.png
baseurl:
url: https://liungkejin.github.io
rss_url:

# Build settings

highlight: true
#highlighter: rouge

timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
